### ISSUE TITLE
import bioviz error

### ISSUE THREAD

**Issue by nashmit** [pyomeca/bioviz#71]
Hi,

After installing bioviz using anaconda I get the following error once I am trying to import this package into python:

> In [2]: import bioviz
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-2-80653c047b29> in <module>
> ----> 1 import bioviz
> 
> ~/anaconda3/envs/msc_thesis/lib/python3.9/site-packages/bioviz/__init__.py in <module>
>      15     import casadi
>      16 import pyomeca
> ---> 17 from .biorbd_vtk import VtkModel, VtkWindow, Mesh, Rototrans
>      18 from PyQt5.QtWidgets import (
>      19     QSlider,
> 
> ~/anaconda3/envs/msc_thesis/lib/python3.9/site-packages/bioviz/biorbd_vtk.py in <module>
>      10 from PyQt5.QtGui import QPalette, QColor
>      11
> ---> 12 from vtk import (
>      13     vtkActor,
>      14     vtkCellArray,
> 
> ~/anaconda3/envs/msc_thesis/lib/python3.9/site-packages/vtk.py in <module>
>      28     import importlib
>      29     # import vtkmodules.all
> ---> 30     all_m = importlib.import_module('vtkmodules.all')
>      31
>      32     # import vtkmodules
> 
> ~/anaconda3/envs/msc_thesis/lib/python3.9/importlib/__init__.py in import_module(name, package)
>     125                 break
>     126             level += 1
> --> 127     return _bootstrap._gcd_import(name[level:], package, level)
>     128
>     129
> 
> ~/anaconda3/envs/msc_thesis/lib/python3.9/site-packages/vtkmodules/all.py in <module>
>      63 from .vtkIOImport import *
>      64 from .vtkIOVideo import *
> ---> 65 from .vtkIOFFMPEG import *
>      66 from .vtkIOExportPDF import *
>      67 from .vtkRenderingGL2PSOpenGL2 import *
> 
> ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory

Any ideas why this is happening?

**Comment by pariterre** [comment]
Hi @nashmit 
I have never seen that error before.. It seems related to VTK... Could you copy-paste the `conda list` output so I can see which version you installed?

**Comment by nashmit** [comment]
This happens under wsl2 ( ubuntu 18.04 ) in win11. Interestingly, this problem doesn't happen under the windows version of anaconda.

`conda list`:

conda list
# packages in environment at /home/nashmit/anaconda3/envs/msc_thesis:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alabaster                 0.7.12             pyhd3eb1b0_0
ampl-mp                   3.1.0             h2cc385e_1006    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0
argh                      0.26.2           py39h06a4308_0
argon2-cffi               20.1.0           py39h27cfd23_1
arrow                     0.13.1           py39h06a4308_0
astroid                   2.6.6            py39h06a4308_0
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     21.2.0             pyhd3eb1b0_0
autopep8                  1.5.7              pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
binaryornot               0.4.4              pyhd3eb1b0_1
biorbd                    1.8.7            py39h34edf50_0    conda-forge
bioviz                    2.1.5           py39_hf3d152e_1    conda-forge
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    4.0.0              pyhd3eb1b0_0
bottleneck                1.3.4            py39hd257fcd_0    conda-forge
brotli                    1.0.9                he6710b0_2
brotlipy                  0.7.0           py39h27cfd23_1003
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.2.1             h06a4308_0
casadi                    3.5.5                    pypi_0    pypi
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.14.6           py39h400218f_0
chardet                   4.0.0           py39h06a4308_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.3              pyhd3eb1b0_0
cloudpickle               2.0.0              pyhd3eb1b0_0
cmake                     3.22.1               h1fce559_0
cocos2d                   0.6.9                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0
cookiecutter              1.7.2              pyhd3eb1b0_0
cryptography              35.0.0           py39hd23ed53_0
curl                      7.80.0               h7f8727e_0
cycler                    0.10.0           py39h06a4308_0
dbus                      1.13.18              hb2f20db_0
debugpy                   1.5.1            py39h295c915_0
decorator                 5.1.0              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
docutils                  0.17.1           py39h06a4308_1
double-conversion         3.2.0                h9c3ff4c_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
entrypoints               0.3              py39h06a4308_0
et_xmlfile                1.1.0            py39h06a4308_0
expat                     2.4.1                h2531618_2
ezc3d                     1.4.7            py39h5472131_0    conda-forge
ffmpeg                    4.2.2                h20bf706_0
flake8                    3.9.2              pyhd3eb1b0_0
fontconfig                2.13.1               h6c09931_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.11.0               h70c0345_0
gettext                   0.21.0               hf68c758_0
giflib                    5.2.1                h7b6447c_0
gl2ps                     1.4.2                h0708190_0    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
glib                      2.69.1               h5202010_0
glm                       0.4.3                    pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.15               he1e5248_0
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
icu                       58.2                 he6710b0_3
idna                      3.3                pyhd3eb1b0_0
imagesize                 1.3.0              pyhd3eb1b0_0
importlib-metadata        4.8.1            py39h06a4308_0
importlib_metadata        4.8.1                hd3eb1b0_0
inflection                0.5.1            py39h06a4308_0
intel-openmp              2021.4.0          h06a4308_3561
intervaltree              3.1.0              pyhd3eb1b0_0
ipopt                     3.14.5               h630875f_0    conda-forge
ipykernel                 6.4.1            py39h06a4308_1
ipython                   7.29.0           py39hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.0           py39h06a4308_1
jeepney                   0.7.1              pyhd3eb1b0_0
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_2
jpeg                      9d                   h7f8727e_0
jsoncpp                   1.9.4                h4bd325d_3    conda-forge
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter                   1.0.0            py39h06a4308_7
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.9.1            py39h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   23.1.0           py39h06a4308_0
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.1            py39h2531618_0
krb5                      1.19.2               h3790be6_4    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lazy-object-proxy         1.6.0            py39h27cfd23_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libcurl                   7.80.0               h0b77cf5_0
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgfortran-ng            11.2.0              h69a702a_13    conda-forge
libgfortran5              11.2.0              h5c6108e_13    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.2                h7f98852_0    conda-forge
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_hcd642e3_100    conda-forge
libnghttp2                1.46.0               hce63b2e_0
libogg                    1.3.5                h27cfd23_1
libopus                   1.3.1                h7f98852_1    conda-forge
libosqp                   0.6.2                h9c3ff4c_3    conda-forge
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h7b6447c_0
libspatialindex           1.9.3                h2531618_0
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libtasn1                  4.18.0               h7f98852_0    conda-forge
libtheora                 1.1.1             h7f98852_1005    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   1.0.3                h7f8727e_2
libuv                     1.43.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.7.0                h439df22_0
libwebp                   1.2.0                h89dd481_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.12               h03d6c58_0
libzip                    1.8.0                h4de3113_1    conda-forge
loguru                    0.5.3            py39hf3d152e_3    conda-forge
lz4-c                     1.9.3                h295c915_1
markupsafe                1.1.1            py39h27cfd23_0
matplotlib                3.4.3            py39hf3d152e_2    conda-forge
matplotlib-base           3.4.3            py39hbbc1b5f_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mccabe                    0.6.1            py39h06a4308_1
metis                     5.1.0             h58526e2_1006    conda-forge
mistune                   0.8.4           py39h27cfd23_1000
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py39h7f8727e_0
mkl_fft                   1.3.1            py39hd3c417c_0
mkl_random                1.2.2            py39h51133e4_0
mumps-include             5.2.1               ha770c72_10    conda-forge
mumps-seq                 5.2.1               h47a8eb5_10    conda-forge
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py39h06a4308_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py39h06a4308_0
nbformat                  5.1.3              pyhd3eb1b0_0
ncurses                   6.3                  h7f8727e_2
nest-asyncio              1.5.1              pyhd3eb1b0_0
nettle                    3.7.3                hbbd107a_1
notebook                  6.4.6            py39h06a4308_0
numpy                     1.21.2           py39h20f2e39_0
numpy-base                1.21.2           py39h79a1101_0
numpydoc                  1.1.0              pyhd3eb1b0_1
olefile                   0.46               pyhd3eb1b0_0
openh264                  2.1.1                h780b84a_0    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1m               h7f8727e_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.1            py39hde0f152_0    conda-forge
pandocfilters             1.4.3            py39h06a4308_1
parso                     0.8.2              pyhd3eb1b0_0
pathspec                  0.7.0                      py_0
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py39h5aabda8_0
pip                       21.2.4           py39h06a4308_0
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
pkgconfig                 1.5.5            py39hf3d152e_1    conda-forge
pluggy                    1.0.0            py39h06a4308_0
poyo                      0.5.0              pyhd3eb1b0_0
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.12.0             pyhd3eb1b0_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
psutil                    5.8.0            py39h27cfd23_1
ptyprocess                0.7.0              pyhd3eb1b0_2
pybox2d                   2.3.10           py39he80948d_1    conda-forge
pycodestyle               2.7.0              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.1.1              pyhd3eb1b0_0
pyflakes                  2.3.1              pyhd3eb1b0_0
pyglet                    1.5.21                   pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0
pylint                    2.9.6            py39h06a4308_1
pyls-spyder               0.4.0              pyhd3eb1b0_0
pyomeca                   2021.0.1           pyh44b312d_0    conda-forge
pyopengl                  3.1.5                    pypi_0    pypi
pyopengl-accelerate       3.1.5                    pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.9.2            py39h2531618_6
pyrsistent                0.18.0           py39heee7806_0
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.7                h12debd9_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-lsp-black          1.0.0              pyhd3eb1b0_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.2.4              pyhd3eb1b0_0
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0
pyxdg                     0.27               pyhd3eb1b0_0
pyyaml                    6.0              py39h7f8727e_1
pyzmq                     22.2.1           py39h295c915_1
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.9.7                h5867ecd_1
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.1.1              pyhd3eb1b0_0
qtpy                      1.10.0             pyhd3eb1b0_0
rbdl                      3.1.3                h4bd325d_0    conda-forge
readline                  8.1                  h27cfd23_0
regex                     2021.8.3         py39h7f8727e_0
requests                  2.26.0             pyhd3eb1b0_0
rhash                     1.4.1                h7f98852_0    conda-forge
rope                      0.21.1             pyhd3eb1b0_0
rtree                     0.9.7            py39h06a4308_1
scipy                     1.8.0            py39hee8e79c_1    conda-forge
scotch                    6.0.9                h3858553_1    conda-forge
secretstorage             3.3.1            py39h06a4308_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py39h06a4308_0
sip                       4.19.13          py39h2531618_0
six                       1.16.0             pyhd3eb1b0_0
slycot                    0.4.0                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
sphinx                    4.2.0              pyhd3eb1b0_1
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.1.5            py39h06a4308_1
spyder-kernels            2.1.3            py39h06a4308_0
sqlite                    3.38.0               hc218d9a_0
swig                      4.0.2                hd3c618e_2    conda-forge
tbb                       2021.5.0             h4bd325d_0    conda-forge
terminado                 0.9.4            py39h06a4308_0
testpath                  0.5.0              pyhd3eb1b0_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
tinyxml                   2.6.2                h4bd325d_2    conda-forge
tk                        8.6.11               h1ccaba5_0
toml                      0.10.2             pyhd3eb1b0_0
tornado                   6.1              py39h27cfd23_0
traitlets                 5.1.1              pyhd3eb1b0_0
typed-ast                 1.4.3            py39h7f8727e_1
typing_extensions         3.10.0.2           pyh06a4308_0
tzdata                    2021e                hda174b7_0
ujson                     4.0.2            py39h2531618_0
unidecode                 1.2.0              pyhd3eb1b0_0
unixodbc                  2.3.9                hb166930_0    conda-forge
urllib3                   1.26.7             pyhd3eb1b0_0
utfcpp                    3.2.1                ha770c72_0    conda-forge
utils                     1.0.1                    pypi_0    pypi
vtk                       9.0.3           py39h0649366_201
watchdog                  2.1.3            py39h06a4308_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39h06a4308_1
wheel                     0.37.0             pyhd3eb1b0_1
whichcraft                0.6.1              pyhd3eb1b0_0
widgetsnbextension        3.5.1            py39h06a4308_0
wrapt                     1.12.1           py39he8ac12f_1
wurlitzer                 2.1.1            py39h06a4308_0
x264                      1!157.20191217       h7b6447c_0
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                h2531618_0
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.5.0                ha4553b6_1

**Comment by pariterre** [comment]
> Interestingly, this problem doesn't happen under the windows version of anaconda. ( same PC )

That definitely seems to be VTK related then. I would not be surprised that the libraries for visualisation are not fully integrated in WSL2... Is there a specific reason you want to use WSL2 instead of native Windows?

**Comment by nashmit** [comment]
Some other project I'm using is not fully integrated into windows, I guess, I will have to make it work under windows too now :) I will take a closer look over VTK lib.

Thanks!

**Comment by pariterre** [comment]
GL!
