### ISSUE TITLE
Dimensions for movement file

### ISSUE THREAD

**Issue by MennatallahRihan** [pyomeca/bioviz#76]
Hey!

I've been trying to make bioviz accept my numpy array of nFrames x nDof and it was giving me an error of being the wrong dimension, but when it was transposed it worked. Just double checking that the dimension is actually nDof x nFrames not as written in the readme file.

**Comment by pariterre** [comment]
Hello!

I confirm that it should be ndof x nframes, can you point the relevant lines (or even modify the readme!) so we don't confuse people :P

**Comment by MennatallahRihan** [comment]
Oh good!
It's here under load movement [GUI section](https://github.com/pyomeca/bioviz#from-the-gui)

**Comment by pariterre** [comment]
There we go! Thanks for reporting :)
